@startuml
skinparam linetype ortho

rectangle "web-browser" {
    [Client Application]
}

rectangle "auth" {
    [Controller] as AuthControllerRec
    [Service] as AuthServiceRec
    [Repository] as AuthRepositoryRec
}

rectangle "AuthControllerRec" {
  [AuthController] <<Controller>>
  [Client Application] ..> [AuthControllerRec] : API calls (HTTP/JSON)

}

rectangle "AuthServiceRec" {
    [AuthService] <<Interface Service>>
    [AuthServiceImpl] <<Service>>

  [AuthService] <--o [AuthController]
  [AuthServiceImpl] ..|> [AuthService]
}

rectangle "AuthRepositoryRec" {
    [AccountRepository] <<Interface Repository>>
    [AccountRepositoryImpl] <<Repository>>

  [AccountRepository] <--o [AuthServiceImpl]
  [AccountRepositoryImpl] ..|> [AccountRepository]
}

database "MySql" {
  frame "db:book-house" {
    [User] <<Table>>
    [Admin] <<Table>>
  }
}

[AccountRepositoryImpl] --> [db:book-house] #Blue

rectangle "core" {
    [Controller] as CoreControllerRec
    [Service] as CoreServiceRec
    [Repository] as CoreRepositoryRec
}

rectangle "CoreControllerRec" {
  [OrderController] <<Controller>>
  [Client Application] ..> [CoreControllerRec] : API calls (HTTP/JSON)
}

rectangle "CoreServiceRec" {
    [OrderService] <<Interface Service>>
    [OrderServiceImpl] <<Service>>

  [OrderService] <--o [OrderController]
  [OrderServiceImpl] ..|> [OrderService]
}

rectangle "CoreRepositoryRec" {
    [ProductRepository] <<Interface Repository>>
    [ProductRepositoryImpl] <<Repository>>

  [ProductRepository] <--o [OrderServiceImpl]
  [ProductRepositoryImpl] ..|> [ProductRepository]
}

[ProductRepositoryImpl] --> [db:book-house] #Blue

@enduml