@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho

class User
class Admin
class Book

enum Role {
    GUEST
    USER
    ADMIN
}

abstract class Account{
    -...
    -Set<Role> setRole
    -Set<Product> setProduct
    -Set<Order> setOrder
}

abstract class Product{
    -...
    -Account account
}

class Order{
    -...
    -Account account
}

class Wallet{
    -...
    -Account account
}
class User{
    -...
}
class Admin{
    -...
}
class Book{
    -...
}

' Relationship between entities '

Account <|-- User
Account <|-- Admin
Account "1" *-- "*" Role : has
Account "1" *-- "*" Product : owns
Product <|-- Book
Product "1" *-- "*" Account : belongs to
Account "1" *-- "*" Order : owns
Order "1" *-- "*" Account : belongs to
Account "1" *-- "*" Wallet : owns
Wallet "1" *-- "*" Account : belongs to

@enduml