@startuml
skinparam linetype ortho

package "auth" {
    interface AuthService {
        +void ordinalRegistration(RegistrationDTO accountDTORequest);
        +void adminRegistration(RegistrationDTO accountDTORequest);
        +Account authorization(AuthorizationDTO authorizationDTORequest);
    }
}


package "core" {
     interface ProductService {
        +boolean createProduct(ProductDTO productDTORequest);
        +boolean editProduct(Long idProduct);
        +boolean deleteProduct(Long idProduct);
        +Product readProduct(Long idProduct);
        +List<Product> readAllProducts();
     }

     interface ProductSortService {
        +List<Product> ascendingSortProducts();
        +List<Product> descendingSortProducts();
     }

     interface ProductOrderService {
        +boolean createOrder(List<Product> listProduct, Long idUser);
     }
}


@enduml