@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor User
actor Guest
actor Admin

package Core{
    (Check products) as (CP)
    (Order products) as (OP)
    (Create products) as (CrP)
    (Delete products) as (DP)
    (Edit products) as (EP)
    (Sort products `Asc-Desc`) as (SP)
}

package Auth{
    (Authorization) as (Author)
    (Registration) as (Reg)
    (Create Admins) as (CA)
    (Authentication) as (Authen)
    (Logout) as (L)
}

User -> (CP)
User ---> (OP)
User -> (Authen)
User --> (SP)
User ---> (L)

Guest ---> (CP)
Guest --> (Reg)
Guest --> (Author)
Guest -> (SP)

Admin ----> (CP)
Admin --> (CA)
Admin ---> (CrP)
Admin ----> (DP)
Admin -> (Authen)
Admin -> (EP)
Admin -> (SP)
Admin -> (L)
@enduml