@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor User
actor Guest
actor Admin

package Core{
    (Check products) as (CP)
    (Order products) as (OP)
}

package Auth{
    (Authorization) as (Author)
    (Registration) as (Reg)
}

User -> (CP)
User -> (OP)
User -> (Author)

Guest ---> (CP)
Guest --> (Reg)

Admin ----> (CP)
Admin ---> (Reg)
Admin ---> (Author)
@enduml