@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor User
actor Guest
actor Admin

package Core{
    (Check products) as (CP)
    (Order products) as (OP)
    (Create products) as (CrP)
    (Delete products) as (DP)
}

package Auth{
    (Authorization) as (Author)
    (Registration) as (Reg)
    (Create Admins) as (CA)
    (Authentication) as (Authen)
}

User -> (CP)
User ---> (OP)
User -> (Author)
User -> (Authen)

Guest ---> (CP)
Guest --> (Reg)

Admin ----> (CP)
Admin ---> (Author)
Admin --> (CA)
Admin ---> (CrP)
Admin ----> (DP)
Admin -> (Authen)
@enduml